
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/ngageoint/simple-features-wkb-ios/discussions
    about: Questions, Feature Requests, Feedback, Conversations
